(()=>{'use strict';
const P='missav-ext-downloader',S='https://surrit.com/',HM='missav-ext-hls-url',CS=[4,8,16,32],D=new Set(),M=new Map();let LU=location.href,T;
const sl=m=>new Promise(r=>setTimeout(r,m)),fn=s=>(String(s||'missav-video').replace(/[\\/:*?"<>|]/g,'').replace(/\s+/g,' ').trim().slice(0,120)||'missav-video');
function title(){return fn(document.querySelector('.order-first .mt-4 h1,.order-first h1,h1')?.textContent||document.title)}
function add(v,m={}){try{const u=new URL(String(v||''),location.href).href;if(!/^https:\/\//i.test(u)||!/\.m3u8(?:[?#]|$)/i.test(u))return null;D.add(u);M.set(u,{...(M.get(u)||{}),...m,url:u});count();return u}catch{return null}}
window.addEventListener('message',e=>{if(e.source===window&&e.origin===location.origin&&e.data?.type===HM)add(e.data.url,{by:'player'})});
const scripts=()=>[...document.scripts].filter(x=>!x.src).map(x=>x.textContent||'').filter(Boolean);
function scan(){for(const e of performance.getEntriesByType('resource'))add(e?.name,{by:'perf'});const re=/https:\/\/[^\s"'<>\\]+?\.m3u8(?:\?[^\s"'<>\\]*)?/ig;for(const r of scripts())for(const m of r.replace(/\\\//g,'/').replace(/&amp;/g,'&').matchAll(re))add(m[0],{by:'script'});document.querySelectorAll('[src],[href],[data-src],[data-url],[data-playlist]').forEach(e=>['src','href','data-src','data-url','data-playlist'].forEach(a=>{const v=e.getAttribute(a);if(v)add(v,{by:'dom'})}))}
function vid(){const a=/https?:\/\/surrit\.com\/([0-9a-f-]{36})/i,b=/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/ig;for(const s of scripts()){const m=s.match(a);if(m)return m[1];const i=s.indexOf('seek'),x=i<0?null:s.slice(Math.max(0,i-600),i).match(b);if(x?.length)return x.at(-1)}return null}
async function txt(u){try{const r=await fetch(u,{credentials:'omit',cache:'no-store',mode:'cors'});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.text()}catch(e){const x=await chrome.runtime.sendMessage({type:'fetch-text',url:u}).catch(()=>null);if(x?.ok)return x.text;throw Error(`${e.message}${x?.error?' / '+x.error:''}`)}}
function at(s){const o={},r=/([A-Z0-9-]+)=("[^"]*"|[^,]*)/gi;for(const m of s.matchAll(r)){let v=m[2]||'';if(v[0]==='"'&&v.at(-1)==='"')v=v.slice(1,-1);o[m[1].toUpperCase()]=v}return o}
function q(u,a={}){const m=a.RESOLUTION?.match(/\d+x(\d+)/);if(m)return m[1]+'p';if(a.NAME)return a.NAME;try{const p=new URL(u).pathname.split('/').filter(Boolean);return decodeURIComponent(p.at(-2)||p.at(-1)||'video')}catch{return'video'}}
function master(t,b){const z=t.split(/\r?\n/).map(x=>x.trim()),o=[];let p=null;for(const l of z){if(!l)continue;if(l.startsWith('#EXT-X-STREAM-INF:')){p=at(l.slice(18));continue}if(l[0]==='#'||(!p&&!/\.m3u8(?:[?#]|$)/i.test(l)))continue;const u=new URL(l,b).href,a=p||{},v={url:u,attrs:a,quality:q(u,a)};add(u,v);o.push(v);p=null}return o}
function br(v,u,m){if(!v)return null;const x=String(v).match(/^(\d+)(?:@(\d+))?$/);if(!x)throw Error('bad BYTERANGE');const n=+x[1],s=x[2]===undefined?(m.get(u)||0):+x[2],e=s+n-1;m.set(u,e+1);return{start:s,end:e,length:n}}
function media(t,b){const o=[],m=new Map();let rg=null,du=0,sq=0;for(const l of t.split(/\r?\n/).map(x=>x.trim())){if(!l)continue;if(l.startsWith('#EXT-X-MEDIA-SEQUENCE:')){sq=+l.slice(22)||0;continue}if(l.startsWith('#EXTINF:')){du=+l.slice(8).split(',')[0]||0;continue}if(l.startsWith('#EXT-X-KEY:')){const x=at(l.slice(11)),k=(x.METHOD||'').toUpperCase();if(k&&k!=='NONE')throw Error('encrypted HLS');continue}if(l.startsWith('#EXT-X-MAP:')){const x=at(l.slice(11));if(x.URI){const u=new URL(x.URI,b).href;o.push({kind:'init',url:u,range:br(x.BYTERANGE,u,m),duration:0})}continue}if(l.startsWith('#EXT-X-BYTERANGE:')){rg=l.slice(17).trim();continue}if(l[0]==='#')continue;const u=new URL(l,b).href;o.push({kind:'media',url:u,range:br(rg,u,m),duration:du,sequence:sq++});rg=null;du=0}const a=o.filter(x=>x.kind==='media');return{items:o,media:a,total:a.reduce((s,x)=>s+x.duration,0)}}
async function resolve(u,w){const t=await txt(u);if(!/#EXT-X-STREAM-INF:/i.test(t))return{url:u,text:t};const a=master(t,u),v=a.find(x=>x.quality===w)||a.find(x=>x.url.includes('/'+w+'/'))||a[0];if(!v)throw Error('no variant');return{url:v.url,text:await txt(v.url)}}
async function remote(){scan();const r=await chrome.runtime.sendMessage({type:'discover-mirror-pages',pathAndQuery:location.pathname+location.search,currentHost:location.hostname}).catch(()=>null);if(r?.ok)for(const u of r.candidates||[])add(u,{by:'mirror'});count();return[...D]}
function compat(a,b){if(a.items.length!==b.items.length||a.media.length!==b.media.length||Math.abs(a.total-b.total)>Math.max(1.5,a.total*.002))return false;for(let i=0;i<a.items.length;i++)if(a.items[i].kind!==b.items[i].kind||Math.abs((a.items[i].duration||0)-(b.items[i].duration||0))>.08||(a.items[i].range?.length||0)!==(b.items[i].range?.length||0))return false;return true}
async function buf(i,n=0){const h={};if(i.range)h.Range=`bytes=${i.range.start}-${i.range.end}`;else if(n)h.Range=`bytes=0-${n-1}`;const r=await fetch(i.url,{credentials:'omit',cache:'no-store',mode:'cors',headers:h});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.arrayBuffer()}
async function hash(b){const h=await crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function same(a,b){if(!compat(a.parsed,b.parsed))return false;const n=a.parsed.items.length,ix=[0,Math.floor(n/2),n-1];for(const i of new Set(ix)){const[x,y]=await Promise.all([buf(a.parsed.items[i],131072),buf(b.parsed.items[i],131072)]);if(await hash(x)!==await hash(y))return false}return true}
const src=(u,p)=>({playlistUrl:u,host:new URL(u).host,parsed:p,st:{bps:0,fail:0,cool:0,flight:0}});
async function sources(u,st){const w=q(u,M.get(u)?.attrs||{}),r=await resolve(u,w),a=src(r.url,media(r.text,r.url)),out=[a];await remote();for(const c of[...D].filter(x=>x!==u&&x!==r.url)){try{st('驗證 '+new URL(c).host+'…');const z=await resolve(c,w);if(out.some(x=>x.playlistUrl===z.url))continue;const s=src(z.url,media(z.text,z.url));if(await same(a,s))out.push(s)}catch{}}return out}
function pick(a,e=new Set()){const n=Date.now(),p=a.filter(x=>!e.has(x)&&x.st.cool<=n),z=p.length?p:a.filter(x=>!e.has(x));z.sort((x,y)=>(y.st.bps||1048576)/(1+y.st.flight*.6)/(1+y.st.fail*.4)-(x.st.bps||1048576)/(1+x.st.flight*.6)/(1+x.st.fail*.4));return z[0]}
async function one(s,i){const x=s.parsed.items[i],h=x.range?{Range:`bytes=${x.range.start}-${x.range.end}`}:{},t=performance.now();s.st.flight++;try{const r=await fetch(x.url,{credentials:'omit',cache:'no-store',mode:'cors',headers:h});if(!r.ok)throw Error(`HTTP ${r.status}`);const b=await r.arrayBuffer(),v=b.byteLength/Math.max((performance.now()-t)/1000,.001);s.st.bps=s.st.bps?s.st.bps*.7+v*.3:v;s.st.fail=Math.max(0,s.st.fail-.25);return b}catch(e){s.st.fail++;s.st.cool=Date.now()+8000*Math.min(4,s.st.fail);throw e}finally{s.st.flight=Math.max(0,s.st.flight-1)}}
async function get(a,i){let e;for(let r=0;r<3;r++){const t=new Set();while(t.size<a.length){const s=pick(a,t);if(!s)break;t.add(s);try{return await one(s,i)}catch(x){e=x}}if(r<2)await sl(500*(r+1))}throw e||Error('all sources failed')}
function fb(n){if(!n)return'0 B';const u=['B','KB','MB','GB','TB'],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),4),v=n/1024**i;return`${v.toFixed(i? (v>=100?0:v>=10?1:2):0)} ${u[i]}`}
const fr=n=>fb(n)+'/s',sum=a=>a.map(s=>s.host+' '+fr(s.st.bps)).join(' + ');
async function pipe(a,w,b,c){const N=a[0].parsed.items.length,K=a[0].parsed.media.length,A=Math.max(c*3,c+4),done=new Map();let ns=0,nw=0,f=0,bytes=0,md=0,err=null,wake,start=performance.now();const sig=()=>{if(wake){const x=wake;wake=null;x()}},pump=()=>{while(!err&&f<c&&ns<N&&ns<nw+A){const i=ns++;f++;get(a,i).then(x=>done.set(i,x)).catch(e=>err=e).finally(()=>{f--;pump();sig()})}};pump();while(nw<N){while(!done.has(nw)){if(err)throw err;await new Promise(r=>wake=r)}const x=done.get(nw);done.delete(nw);await w.write(x);bytes+=x.byteLength;if(a[0].parsed.items[nw].kind==='media')md++;nw++;pump();const e=Math.max((performance.now()-start)/1000,.001);b.textContent=`${K?Math.round(md/K*100):0}% · ${fb(bytes)} · ${fr(bytes/e)} · ${a.length}來源`;b.title=sum(a)}return{bytes,sec:Math.max((performance.now()-start)/1000,.001)}}
const cv=()=>{const n=+document.querySelector('#'+P+' .mav-ext-concurrency')?.value;return CS.includes(n)?n:16};
async function cp(s){try{await navigator.clipboard.writeText(s)}catch{const t=document.createElement('textarea');t.value=s;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}}
function cmd(u,n){return`N_m3u8DL-RE "${u}" -H "Referer: ${location.href}" -H "Origin: ${location.origin}" -H "User-Agent: ${navigator.userAgent}" --save-dir "$env:USERPROFILE\\Downloads" --save-name "${fn(n)}" --download-retry-count 10 --thread-count ${cv()} -M format=mp4`}
async function dl(u,n,b,info){const o=b.textContent;let w;try{if(typeof showSaveFilePicker!=='function')throw Error('需要桌面版 Chrome/Brave File System Access API');const h=await showSaveFilePicker({suggestedName:n.toLowerCase().endsWith('.mp4')?n:n+'.mp4',types:[{description:'Video',accept:{'video/mp4':['.mp4']}}]});b.disabled=true;const a=await sources(u,s=>info.textContent=s);info.textContent=a.length>1?'多來源：'+sum(a):'只有 1 個可驗證來源：'+a[0].host;w=await h.createWritable();const r=await pipe(a,w,b,cv());await w.close();w=null;info.textContent='完成 · '+sum(a);b.textContent=`完成 · ${fb(r.bytes)} · ${fr(r.bytes/r.sec)}`}catch(e){if(w)try{await w.abort()}catch{}if(e?.name!=='AbortError'){info.textContent='失敗：'+(e.message||e);b.textContent='失敗';alert('下載失敗：'+(e.message||e))}}finally{setTimeout(()=>{b.disabled=false;b.textContent=o},1800)}}
function count(x=''){const e=document.querySelector('#'+P+' .mav-ext-source-counter');if(!e)return;const h=new Set([...D].map(u=>{try{return new URL(u).host}catch{return''}}).filter(Boolean));e.textContent=`偵測 ${D.size} 個 HLS URL / ${h.size} 個主機${x?' · '+x:''}`}
function mount(){return document.querySelector('.order-first .mt-4,.order-first,main,body')}
function panel(m){let r=document.getElementById(P);if(r)return r;r=document.createElement('section');r.id=P;r.innerHTML=`<div class="mav-ext-header"><div><div class="mav-ext-title">MissAV 多來源影片下載</div><div class="mav-ext-source-counter"></div></div><div class="mav-ext-header-right"><label class="mav-ext-thread-control">下載執行緒 <select class="mav-ext-concurrency"><option>4</option><option>8</option><option selected>16</option><option>32</option></select></label><button class="mav-ext-btn scan">重新掃描來源</button><button class="mav-ext-btn add">加入鏡像 m3u8</button></div></div><div class="mav-ext-status">初始化…</div><div class="mav-ext-list"></div>`;m.appendChild(r);r.querySelector('.scan').onclick=async e=>{e.target.disabled=true;try{await remote();count('已重新掃描')}finally{e.target.disabled=false}};r.querySelector('.add').onclick=()=>{const u=prompt('輸入 HTTPS m3u8 URL：');if(u)count(add(u,{by:'manual'})?'已加入':'URL 無效')};count();return r}
function row(l,v,n){const r=document.createElement('div');r.className='mav-ext-item';const a=document.createElement('div');a.className='mav-ext-quality';a.textContent=v.quality||q(v.url,v.attrs||{});const u=document.createElement('div');u.className='mav-ext-url';u.textContent=v.url;u.title=v.url;const i=document.createElement('div');i.className='mav-ext-source-info';i.textContent='下載時自動搜尋並驗證 HLS mirror';const x=document.createElement('div');x.className='mav-ext-actions';for(const[t,f,k]of[['複製連結',()=>cp(v.url+'#'+n),''],['多來源下載',()=>dl(v.url,n,d,i),'mav-ext-btn-primary'],['複製外部指令',()=>cp(cmd(v.url,n)),'']]){const d=document.createElement('button');d.className='mav-ext-btn '+k;d.type='button';d.textContent=t;d.onclick=f;x.appendChild(d)}r.append(a,u,i,x);l.appendChild(r)}
async function init(n=0){const m=mount();if(!m){if(n<20)T=setTimeout(()=>init(n+1),500);return}const r=panel(m),s=r.querySelector('.mav-ext-status'),l=r.querySelector('.mav-ext-list');l.textContent='';scan();const id=vid();if(!id){s.textContent='尚未找到影片來源';if(n<20)T=setTimeout(()=>init(n+1),500);return}const u=add(new URL(id+'/playlist.m3u8',S).href,{by:'primary'});try{s.textContent='正在讀取畫質清單…';const t=await txt(u);let a=master(t,u);if(!a.length&&!/#EXT-X-STREAM-INF:/i.test(t))a=[{url:u,attrs:{},quality:q(u)}];if(!a.length)throw Error('主播放清單沒有可用畫質');for(const v of a)row(l,v,title());s.textContent=`找到 ${a.length} 個畫質`;remote().catch(()=>{})}catch(e){const a=[...D].filter(x=>/\/video\.m3u8(?:[?#]|$)/i.test(x));if(a.length){for(const z of a)row(l,{url:z,attrs:{},quality:q(z)},title());s.textContent=`從播放器找到 ${a.length} 個畫質`}else{s.textContent='讀取失敗';const z=document.createElement('div');z.className='mav-ext-error';z.textContent=e.message||e;l.appendChild(z)}}}
function reset(){clearTimeout(T);document.getElementById(P)?.remove();D.clear();M.clear();init()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init(),{once:true});else init();new MutationObserver(()=>{if(location.href!==LU){LU=location.href;reset()}}).observe(document.documentElement,{subtree:true,childList:true});
})();
